server:
  port: 7004

logging:
  level:
    org.springframework: info
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: debug

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: pp-service-rs
          uri: lb:ws://pp-service
          predicates:
            - Path=/pp-service-rsocket
          filters:
            - SetPath=/rsocket
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          include-expression: "!serviceId.equals('CONFIG-SERVICE')"
          routes:
            - id: swagger-route
              predicates:
                - name: Path
                  args:
                    pattern: "'/'+serviceId+'-swagger/**'"
              filters:
                - name: AddRequestHeader
                  args:
                    name: "'X-Forwarded-Prefix'"
                    value: "'/' + serviceId"
                - name: RewritePath
                  args:
                    regexp: "'/' + serviceId + '-swagger/?(?<remaining>.*)'"
                    replacement: "'/' + serviceId + '-swagger/${remaining}'"
  sleuth:
    sampler:
      probability: 1
  zipkin:
    enabled: true
    baseUrl: http://localhost:7411/
  logstash:
    host: localhost
    port: 7500


eureka:
  client:
    registerWithEureka: false
    registryFetchIntervalSeconds: 10
    serviceUrl:
      defaultZone: http://localhost:7002/eureka/

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway