apiVersion: v1
kind: Namespace
metadata: 
  name: acme-dev
  labels: 
    name: acme-dev    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: acme-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi     
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: acme-dev
spec:
  selector:
    matchLabels:
      app: jenkins
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: acme-jenkins:2.303.2-lts-jdk11
        env:
        - name: DOCKER_TLS_VERIFY
          value: "1"
        - name: DOCKER_HOST
          value: "tcp://192.168.49.2:2376"
        - name: DOCKER_CERT_PATH
          value: "/var/jenkins_home/minikube-certs"
        - name: MINIKUBE_ACTIVE_DOCKERD
          value: "minikube"                              
        resources:
          limits:
            memory: "1500Mi"         
        ports:
        - containerPort: 8080
          name: jenkins-http
        volumeMounts:
        - name: jenkins-storate
          mountPath: /var/jenkins_home
      volumes:
      - name: jenkins-storate
        persistentVolumeClaim:
          claimName: jenkins-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: acme-dev
spec:
  type: ClusterIP
  selector:
    app: jenkins
  ports:
    - port: 8080
      targetPort: 8080