version: '3.1'

services:
  mongo:
    image: mongo:4.0.9
    container_name: acme-pr-mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: prUser
      MONGO_INITDB_ROOT_PASSWORD: prPass

  mongo-express:
    image: mongo-express
    container_name: acme-pr-mongodb-ui
    ports:
      - 7000:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: prUser
      ME_CONFIG_MONGODB_ADMINPASSWORD: prPass

networks:
  default:
    external:
      name: acme-network
