version: '3.1'

services:
  mongo:
    image: mongo:4.0.9
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: prUser
      MONGO_INITDB_ROOT_PASSWORD: prPass

  mongo-express:
    image: mongo-express
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: prUser
      ME_CONFIG_MONGODB_ADMINPASSWORD: prPass