pipeline {
  agent any

  tools {
     jdk 'jdk-11'
     maven 'maven-3.8'
  }

  environment {
    subModule = "discovery-service"
    pomFile = "${subModule}/pom.xml"
    pom = readMavenPom(file: pomFile)
    imageName = pom.getProperties().getProperty("docker.image.name")
    appVersion = pom.getVersion()
  }

  stages {
    // workaround to avoid git detached state otherwise maven git doesn't pull branch name
    stage('Checkout') {
      steps {
        script {
          sh "git fetch"
          sh "git checkout ${env.branch}"
          sh "git pull | exit 0"
        }
      }
    }
    
    stage('Build App') {
      steps {
        dir(env.subModule) {
          sh 'mvn clean install'
        }
        script {
          sh "echo ${imageName}:${appVersion}"
          sh "docker build -t ${imageName}:${appVersion} ${subModule}"
        }
      }
    }
  }
}