server:
  port: 7002

eureka:
  server:
    enableSelfPreservation: false
    expectedClientRenewalIntervalSeconds:  5
    evictionIntervalTimerInMs: 2000
    responseCacheAutoExpirationInSeconds: 1
    responseCacheUpdateIntervalMs: 1000
  client:
    registerWithEureka: false
    fetchRegistry: false