pipeline {
  agent any

  environment {
    subModule = "admin-ui"
    imageName = "acme-system/admin-ui"
    packageJson = readJSON(file: "admin-ui/package.json") 
    appVersion = "${packageJson.version}"
  }

  stages {
    // workaround to avoid git detached state otherwise maven git doesn't pull branch name
    stage('Checkout') {
      steps {
        script {
          sh "git fetch"
          sh "git checkout ${env.branch}"
          sh "git pull | exit 0"
        }
      }
    }
    
    stage('Build App') {
      steps {
        dir(env.subModule) {
          sh "echo ${imageName}:${appVersion}"
          sh "docker build -t ${imageName}:${appVersion} ."
        }
      }
    }
  }
}