logging:
  level:
    org.springframework: info
    io.r2dbc.postgresql.QUERY: debug

spring:
  application:
    name: accounting-service
  config:
    import: configserver:http://config-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-service

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    initialInstanceInfoReplicationIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 10
    serviceUrl:
      defaultZone: http://localhost:7002/eureka/