apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounting-service
  namespace: acme
spec:
  selector:
    matchLabels:
      app: accounting-service
  replicas: 1
  template:
    metadata:
      labels:
        app: accounting-service
    spec:
      containers:
      - name: accounting-service
        image: acme-system/accounting-service:1.0-SNAPSHOT
        env:
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            value: "http://discovery-service:7002/eureka/"
          - name: EUREKA_INSTANCE_PREFERIPADDRESS
            value: "true"
          - name: SPRING_PROFILES_ACTIVE
            value: "lk8s"
        resources:
          limits:
            memory: "800Mi"
        ports:
        - containerPort: 7010
          name: http