apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-ui
  namespace: acme
spec:
  selector:
    matchLabels:
      app: client-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: client-ui
    spec:
      containers:
      - name: client-ui
        image: acme-system/client-ui:1.0.0-SNAPSHOT
        ports:
        - containerPort: 80
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: client-ui
  namespace: acme
spec:
  type: ClusterIP
  selector:
    app: client-ui
  ports:
    - port: 80
      targetPort: 80          