apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  namespace: acme
spec:
  selector:
    matchLabels:
      app: config-service
  replicas: 1
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
      - name: config-service
        image: acme-system/config-service:1.0-SNAPSHOT
        env:
          - name: eureka.client.serviceUrl.defaultZone
            value: "http://discovery-service.acme:7002/eureka/"
        ports:
        - containerPort: 7000
          name: http