---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-pvc
  namespace: acme
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: acme
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-db
  namespace: acme
spec:
  selector:
    matchLabels:
      app: pg-db
  replicas: 1
  template:
    metadata:
      labels:
        app: pg-db
    spec:
      containers:
        - name: pg-db
          image: postgres:13.3-alpine
          env:
            - name: POSTGRES_USER
              value: "acmeUser"
            - name: POSTGRES_PASSWORD
              value: "@acmePas2"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pg-storate
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pg-storate
          persistentVolumeClaim:
            claimName: pg-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: pg-db
  namespace: acme
spec:
  type: ClusterIP
  selector:
    app: pg-db
  ports:
    - port: 5432
      targetPort: 5432