apiVersion: v1
kind: Service
metadata:
  name: hl-ds
  namespace: acme
spec:
  ports:
  - port: 7002
    name: http
  clusterIP: None
  selector:
    app: discovery-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ds-config
  namespace: acme
data:
  application.yml: |
    spring:
      application:
        name: discovery-service
    eureka:
      server:
        enableSelfPreservation: true
      client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
          defaultZone: http://discovery-service-0.hl-ds:7002/eureka/,http://discovery-service-1.hl-ds:7002/eureka/
      instance:
        hostname: ${HOSTNAME}.hl-ds
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: discovery-service
  namespace: acme
spec:
  selector:
    matchLabels:
      app: discovery-service
  replicas: 2
  serviceName: hl-ds
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
      - name: discovery-service
        image: acme-system/discovery-service:1.0-SNAPSHOT
        env:
          - name: JAVA_OPTS
            value: "-Xmx100m"
          - name: SPRING_PROFILES_ACTIVE
            value: "cluster"
        ports:
          - containerPort: 7002
            name: http
        volumeMounts:
          - name: config
            mountPath: "/app/config"
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: ds-config
            items:
              - key: "application.yml"
                path: "application.yml"
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: acme
spec:
  type: ClusterIP
  selector:
    app: discovery-service
  ports:
    - port: 7002
      targetPort: 7002