apiVersion: apps/v1
kind: Deployment
metadata:
  name: info-service
  namespace: acme
spec:
  selector:
    matchLabels:
      app: info-service
  replicas: 1
  template:
    metadata:
      labels:
        app: info-service
    spec:
      containers:
      - name: info-service
        image: acme-system/info-service:1.0-SNAPSHOT
        env:
          - name: eureka.client.serviceUrl.defaultZone
            value: "http://discovery-service:7002/eureka/"
        ports:
        - containerPort: 7006
          name: http