server:
  port: 7001

spring:
  data:
    rest:
      basePath: /api

logging:
  level:
    org.springframework: info

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:7761/eureka/