version: '3.1'

services:
  db:
    image: mongo:5.0.2
    container_name: acme-rfd-db
    ports:
      - 7021:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: rfUser
      MONGO_INITDB_ROOT_PASSWORD: rfPass

  db-ui:
    image: mongo-express:0.54.0
    container_name: acme-rfd-db-ui
    ports:
      - 7022:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rfUser
      ME_CONFIG_MONGODB_ADMINPASSWORD: rfPass

networks:
  default:
    external:
      name: acme-network
