version: '3.1'

services:
  db:
    image: mongo:5.0.2
    container_name: acme-mn-db
    ports:
      - 7051:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mnUser
      MONGO_INITDB_ROOT_PASSWORD: mnPass

  db-ui:
    image: mongo-express:0.54.0
    container_name: acme-mn-db-ui
    ports:
      - 7052:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: acme-mb-db
      ME_CONFIG_MONGODB_ADMINUSERNAME: mnUser
      ME_CONFIG_MONGODB_ADMINPASSWORD: mnPass

networks:
  default:
    external:
      name: acme-network
