server:
  port: 7004

logging:
  level:
    org.springframework: info

spring:
  application:
    name: info-service
  config:
    import: configserver:http://config-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7002/eureka/