server:
  port: 7006

logging:
  level:
    org.springframework: info

spring:
  application:
    name: info-service
    id: ${random.uuid}
  config:
    import: configserver:http://config-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-service

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 16
  client:
    initialInstanceInfoReplicationIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:7002/eureka/
