version: '3.1'

services:
  db:
    image: postgres:13.3-alpine
    container_name: acme-user-db
    ports:
      - 7011:5432
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: usUser
      POSTGRES_PASSWORD: usPass


networks:
  default:
    external:
      name: acme-network
