server:
  port: 7050

logging:
  level:
    org.springframework: info

spring:
  application:
    name: menu-service
  config:
    import: configserver:http://config-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-service
  liquibase:
    enabled: true
    change-log: db/changelog/master.xml
    url: ${catalog-srv.db.uri}
  data:
    mongodb:
      host: ${catalog-srv.db.host}
      port: ${catalog-srv.db.port}
      database: ${catalog-srv.db.database}
      username: ${catalog-srv.db.username}
      password: ${catalog-srv.db.password}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 16
  client:
    initialInstanceInfoReplicationIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:7002/eureka/

catalog-srv:
  db:
    host: localhost
    port: 7051
    database: menusrv
    username: mnUser
    password: mnPass
    uri: mongodb://${catalog-srv.db.username}:${catalog-srv.db.password}@${catalog-srv.db.host}:${catalog-srv.db.port}/${catalog-srv.db.database}
  security:
    jwt:
      public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhUcCJmSMOfqkKJemWl2/Z25kWVMNfim9KoGjOR+lrKTsvlELNpslyZtwPOhE1P4b2PpU9lmX8Z5y+FsEl0xgUqqnYvQXulA8W6/1N41dBvHXozZUFXvY9/sO6bSlzoUND/tuU7+CGEmqX0ZVDScPboGgfX2O0qgOS9TrdGGwfZ6d4Ujc6HMxgCVIBsuGTKd57Zst1useJB95ca14NI3GXaNG8feXf4MTnaNT7yxLZyNNn9fXvt5qdkfT1qjNDxa39YiU8hlVZ9XPSTakwoFfhZbXN0umNKvoQ4D1kI2nFKOgpPLdrxx9TNIJ2s2lUhqw/PPPaze1nHi3yMqY2Bdu0wIDAQAB