server:
  port: 7000

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sergey-kulak/acme-config-repo

eureka:
  ##instance:
  ##  preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:7002/eureka/