version: '3.1'

services:
  db:
    image: postgres:13.3-alpine
    container_name: acme-pp-db
    ports:
      - 7041:5432
    environment:
      POSTGRES_DB: ppdb
      POSTGRES_USER: ppUser
      POSTGRES_PASSWORD: ppPass


networks:
  default:
    external:
      name: acme-network
